# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

moments_ctmcjumps <- function(edge_lengths, rate_mat, label_mat, num_edges, num_states) {
    .Call('phylomoments_moments_ctmcjumps', PACKAGE = 'phylomoments', edge_lengths, rate_mat, label_mat, num_edges, num_states)
}

ctmc_sim <- function(t, rate_mat, init_state) {
    .Call('phylomoments_ctmc_sim', PACKAGE = 'phylomoments', t, rate_mat, init_state)
}

int_states_sim <- function(edge_mat, edge_lengths, rate_mat, root_dist, num_edges, num_states, num_term_nodes, tip_data, N) {
    .Call('phylomoments_int_states_sim', PACKAGE = 'phylomoments', edge_mat, edge_lengths, rate_mat, root_dist, num_edges, num_states, num_term_nodes, tip_data, N)
}

prior_moments_phylojumps <- function(edge_mat, edge_set, root_dist, num_edges, num_states, num_term_nodes, edge_moments) {
    .Call('phylomoments_prior_moments_phylojumps', PACKAGE = 'phylomoments', edge_mat, edge_set, root_dist, num_edges, num_states, num_term_nodes, edge_moments)
}

post_moments_phylojumps <- function(edge_mat, edge_set, root_dist, num_edges, num_states, num_term_nodes, edge_moments, seq_data) {
    .Call('phylomoments_post_moments_phylojumps', PACKAGE = 'phylomoments', edge_mat, edge_set, root_dist, num_edges, num_states, num_term_nodes, edge_moments, seq_data)
}

find_subtree_edges <- function(node, edge_mat) {
    .Call('phylomoments_find_subtree_edges', PACKAGE = 'phylomoments', node, edge_mat)
}

tips_sim <- function(edge_mat, edge_lengths, rate_mat, root_dist, num_edges, num_states, num_term_nodes, N) {
    .Call('phylomoments_tips_sim', PACKAGE = 'phylomoments', edge_mat, edge_lengths, rate_mat, root_dist, num_edges, num_states, num_term_nodes, N)
}

phylojumps_sim <- function(edge_mat, edge_lengths, rate_mat, root_dist, num_edges, num_states, num_term_nodes, seq_data, N) {
    .Call('phylomoments_phylojumps_sim', PACKAGE = 'phylomoments', edge_mat, edge_lengths, rate_mat, root_dist, num_edges, num_states, num_term_nodes, seq_data, N)
}

postmean_moments_phylojumps <- function(edge_mat, edge_lengths, rate_mat, edge_set, root_dist, num_edges, num_states, num_term_nodes, edge_moments, N) {
    .Call('phylomoments_postmean_moments_phylojumps', PACKAGE = 'phylomoments', edge_mat, edge_lengths, rate_mat, edge_set, root_dist, num_edges, num_states, num_term_nodes, edge_moments, N)
}

joint_prior_moments_phylojumps <- function(edge_mat, edge_set1, edge_set2, root_dist, num_edges, num_states, num_term_nodes, edge_moments) {
    .Call('phylomoments_joint_prior_moments_phylojumps', PACKAGE = 'phylomoments', edge_mat, edge_set1, edge_set2, root_dist, num_edges, num_states, num_term_nodes, edge_moments)
}

joint_post_moments_phylojumps <- function(edge_mat, edge_set1, edge_set2, root_dist, num_edges, num_states, num_term_nodes, edge_moments, seq_data) {
    .Call('phylomoments_joint_post_moments_phylojumps', PACKAGE = 'phylomoments', edge_mat, edge_set1, edge_set2, root_dist, num_edges, num_states, num_term_nodes, edge_moments, seq_data)
}

joint_postmean_moments_phylojumps <- function(edge_mat, edge_lengths, rate_mat, edge_set1, edge_set2, root_dist, num_edges, num_states, num_term_nodes, edge_moments, N) {
    .Call('phylomoments_joint_postmean_moments_phylojumps', PACKAGE = 'phylomoments', edge_mat, edge_lengths, rate_mat, edge_set1, edge_set2, root_dist, num_edges, num_states, num_term_nodes, edge_moments, N)
}

